import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { FALLBACK_BLOGS } from '../src/data/staticBlogs.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const BASE_URL = 'https://fullematematigi.com.tr';
const DIST_DIR = path.resolve(__dirname, '../dist');
const PUBLIC_DIR = path.resolve(__dirname, '../public');

// Base HTML template generated by Vite build
const indexHtmlPath = path.join(DIST_DIR, 'index.html');
if (!fs.existsSync(indexHtmlPath)) {
  console.error('Error: dist/index.html does not exist. Run vite build first.');
  process.exit(1);
}

const baseHtmlTemplate = fs.readFileSync(indexHtmlPath, 'utf8');

// Helper to sanitize HTML tags for plaintext extracts
function stripTags(html) {
  return html ? html.replace(/<[^>]*>/g, '').replace(/\s+/g, ' ').trim() : '';
}

// 1. Static site routes definition
const STATIC_PAGES = [
  {
    path: '/',
    title: 'KPSS, LGS, TYT, AYT Matematik Online Ders & Özel Ders | Fullematematiği',
    description: 'KPSS online ders, LGS online ders, TYT ve AYT matematik online özel ders platformu Fullematematiği ile sınavlara derece hedefiyle hazırlanın. İlk canlı tanışma dersiniz ücretsiz!',
    keywords: 'kpss online ders, lgs online ders, tyt online ders, ayt online ders, kpss matematik online ders, lgs matematik online ders, tyt matematik online ders, ayt matematik online ders, matematik online özel ders, Fullematematiği',
    heading: 'Matematik Online Özel Ders & Canlı Ders Platformu',
    intro: 'Türkiye\'nin 1 numaralı matematik online özel ders ve canlı ders platformu Fullematematiği ile YKS, LGS ve KPSS\'de netlerinizi zirveye taşıyın. Birebir özel anlatım, uzman hoca desteği ve 7/24 ders kayıt izleme avantajı.',
    type: 'website',
    priority: '1.0',
    changefreq: 'daily'
  },
  {
    path: '/blog',
    title: 'Matematik Rehberleri & Sınav Taktikleri | Fullematematiği Blog',
    description: 'LGS, TYT, AYT ve KPSS matematik ve geometri konu anlatımları, 9. sınıf müfredatı, soru dağılımları ve derece çalışma rehberleri.',
    keywords: 'matematik konuları, tyt matematik konuları, lgs matematik konuları, 9 sınıf matematik konuları, geometri taktikleri, matematik rehberleri',
    heading: 'Matematik & Sınav Başarı Rehberleri',
    intro: 'LGS, TYT, AYT ve KPSS hazırlığında konu anlatımları, güncel müfredat detayları, soru dağılımları ve derece taktikleri.',
    type: 'website',
    priority: '0.9',
    changefreq: 'daily'
  },
  {
    path: '/derslerimiz',
    title: 'Online Matematik Canlı Ders Kampları & Özel Ders | Fullematematiği',
    description: 'YKS, LGS ve KPSS için online matematik canlı ders paketleri ve geometri kampları. Sınıf seviyenize en uygun canlı dersi seçin, ilk ders ücretsiz!',
    keywords: 'matematik canlı ders, online matematik canlı ders, geometri canlı ders, YKS matematik canlı ders, LGS matematik canlı ders, KPSS matematik canlı ders, matematik canlı kurs',
    heading: 'Sınavlara Fullematematiği Canlı Ders Kampları ile Hazırlanın',
    intro: 'Ortaokul LGS, YKS ve KPSS sınavlarına hazırlıkta uzman öğretmen kadromuzla canlı Zoom eğitimleri, çözümlü ders notları ve birebir ödev takibi.',
    type: 'website',
    priority: '0.8',
    changefreq: 'weekly'
  },
  {
    path: '/pdf-notlari',
    title: 'Canlı Ders PDF Matematik Notları ve Geometri Testleri | Fullematematiği',
    description: 'Online matematik canlı ders notları, geometri formül kağıtları, YKS, LGS, KPSS ve okul seviyelerine özel çözümlü PDF fasikülleri ücretsiz indirin!',
    keywords: 'matematik canlı ders pdf, online matematik pdf notları, geometri ders notları pdf, YKS matematik canlı ders notu, LGS matematik canlı ders pdf',
    heading: 'Ücretsiz Matematik PDF Ders Notları ve Testler',
    intro: 'Uzman öğretmen kadromuz tarafından hazırlanan LGS, YKS ve KPSS matematik ders fasiküllerine ücretsiz ulaşabilirsiniz.',
    type: 'website',
    priority: '0.8',
    changefreq: 'weekly'
  },
  {
    path: '/camps',
    title: 'Matematik Kamp Programları | Fullematematiği',
    description: 'LGS, YKS ve KPSS hazırlığı için yeni nesil soru çözüm kampları ve canlı grup dersleri.',
    keywords: 'matematik kampı, lgs matematik kampı, kpss matematik kampı, tyt matematik kampı',
    heading: 'Özel Matematik ve Geometri Kamp Programları',
    intro: 'Netlerinizi kısa sürede artırmak için özel olarak tasarlanmış yoğun matematik ve geometri kamplarımız.',
    type: 'website',
    priority: '0.7',
    changefreq: 'weekly'
  },
  {
    path: '/kontenjan-kurslari',
    title: 'Kontenjanlı Özel Matematik Kursları | Fullematematiği',
    description: 'Sınırlı kontenjanlı online matematik canlı ders grupları ve birebir koçluk destekli eğitim paketleri.',
    keywords: 'kontenjanlı matematik kursu, online matematik grubu, birebir matematik koçluğu',
    heading: 'Kontenjanlı Canlı Ders Grupları',
    intro: 'Butik sınıflarda birebir ilgi ile matematik netlerinizi yükseltin.',
    type: 'website',
    priority: '0.7',
    changefreq: 'weekly'
  },
  {
    path: '/kontenjan-dersleri',
    title: 'Kontenjanlı Matematik Ders Seçimi | Fullematematiği',
    description: 'LGS, YKS, KPSS ve Lise matematik seviyenize uygun sınırlı kontenjanlı canlı ders grupları.',
    keywords: 'kontenjanlı ders seçimi, online matematik canlı ders, lgs ders seçimi',
    heading: 'Kontenjanlı Canlı Ders Grupları',
    intro: 'Sınıf seviyenize en uygun butik grubu seçerek derslerinize hemen başlayın.',
    type: 'website',
    priority: '0.7',
    changefreq: 'weekly'
  },
  {
    path: '/iletisim',
    title: 'İletişim & Ücretsiz Tanışma Dersi Başvurusu | Fullematematiği',
    description: 'Fullematematiği online matematik özel ders platformu iletişim bilgileri, telefon numarası ve WhatsApp randevu hattı.',
    keywords: 'fullematematiği iletişim, matematik özel ders başvuru, tanışma dersi randevu',
    heading: 'Bizimle İletişime Geçin',
    intro: 'Canlı tanışma dersi başvurusu ve eğitim paketlerimiz hakkında bilgi almak için 0535 059 89 50 numaralı telefondan veya WhatsApp üzerinden ulaşabilirsiniz.',
    type: 'website',
    priority: '0.5',
    changefreq: 'monthly'
  },
  {
    path: '/kvkk',
    title: 'KVKK ve Gizlilik Politikası | Fullematematiği',
    description: 'Fullematematiği Kişisel Verilerin Korunması Kanunu (KVKK) aydınlatma metni ve gizlilik politikası.',
    keywords: 'fullematematiği kvkk, gizlilik politikası',
    heading: 'KVKK ve Gizlilik Politikası',
    intro: 'Kişisel verilerinizin korunması ve işlenmesi ile ilgili yasal haklarınız ve politikalarımız.',
    type: 'website',
    priority: '0.3',
    changefreq: 'monthly'
  }
];

// Helper to construct structured HTML for Googlebot pre-rendering
function generatePageHtml(meta) {
  const fullTitle = meta.title.includes('Fullematematiği') ? meta.title : `${meta.title} | Fullematematiği`;
  const canonicalUrl = meta.path === '/' ? `${BASE_URL}/` : `${BASE_URL}${meta.path}`;
  const ogImage = meta.image ? (meta.image.startsWith('http') ? meta.image : `${BASE_URL}${meta.image.startsWith('/') ? '' : '/'}${meta.image}`) : `${BASE_URL}/logo.png`;
  
  const isArticle = meta.type === 'article';
  const robotsContent = meta.noindex ? 'noindex, nofollow' : 'index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1';

  // Construct Breadcrumb items
  const breadcrumbItems = [
    { '@type': 'ListItem', position: 1, name: 'Ana Sayfa', item: `${BASE_URL}/` }
  ];

  if (meta.path !== '/') {
    const segments = meta.path.split('/').filter(Boolean);
    let curr = '';
    segments.forEach((seg, idx) => {
      curr += `/${seg}`;
      let name = seg === 'blog' ? 'Blog' : seg.replace(/-/g, ' ');
      if (idx === segments.length - 1 && meta.h1Title) {
        name = meta.h1Title;
      } else {
        name = name.charAt(0).toUpperCase() + name.slice(1);
      }
      breadcrumbItems.push({
        '@type': 'ListItem',
        position: idx + 2,
        name: name,
        item: `${BASE_URL}${curr}`
      });
    });
  }

  const breadcrumbSchema = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    '@id': `${canonicalUrl}#breadcrumb`,
    itemListElement: breadcrumbItems
  };

  let schemaGraph = [];

  if (isArticle) {
    schemaGraph = [
      {
        '@type': 'BlogPosting',
        '@id': `${canonicalUrl}#article`,
        isPartOf: { '@id': `${BASE_URL}/blog` },
        headline: meta.h1Title || meta.title,
        description: meta.description,
        url: canonicalUrl,
        mainEntityOfPage: { '@type': 'WebPage', '@id': canonicalUrl },
        image: ogImage,
        datePublished: meta.publishedAt || '2026-08-01T10:00:00.000Z',
        dateModified: meta.updatedAt || meta.publishedAt || '2026-08-18T10:00:00.000Z',
        author: {
          '@type': 'Organization',
          name: meta.authorName || 'Fullematematiği Eğitim Kadrosu',
          url: BASE_URL
        },
        publisher: {
          '@type': 'EducationalOrganization',
          name: 'Fullematematiği',
          logo: { '@type': 'ImageObject', url: `${BASE_URL}/logo.png` }
        },
        inLanguage: 'tr-TR'
      },
      breadcrumbSchema
    ];

    if (meta.faq && meta.faq.length > 0) {
      schemaGraph.push({
        '@type': 'FAQPage',
        '@id': `${canonicalUrl}#faq`,
        mainEntity: meta.faq.map(item => ({
          '@type': 'Question',
          name: item.question,
          acceptedAnswer: {
            '@type': 'Answer',
            text: item.answer
          }
        }))
      });
    }
  } else {
    schemaGraph = [
      {
        '@type': 'WebSite',
        '@id': `${BASE_URL}/#website`,
        url: `${BASE_URL}/`,
        name: 'Fullematematiği',
        description: 'Türkiye\'nin LGS, TYT, AYT ve KPSS online matematik ve geometri platformu.',
        inLanguage: 'tr-TR'
      },
      {
        '@type': 'EducationalOrganization',
        '@id': `${BASE_URL}/#organization`,
        name: 'Fullematematiği',
        url: `${BASE_URL}/`,
        logo: `${BASE_URL}/logo.png`,
        image: ogImage,
        description: 'Türkiye\'de LGS, TYT, AYT ve KPSS öğrencileri için online matematik konu anlatımı, özel ders ve rehberlik platformu.',
        sameAs: [
          'https://www.instagram.com/fullematematigi',
          'https://www.youtube.com/@FULLEMATEMAT%C4%B0G%C4%B0'
        ]
      },
      breadcrumbSchema
    ];
  }

  const jsonLdHtml = `<script type="application/ld+json">\n${JSON.stringify({ '@context': 'https://schema.org', '@graph': schemaGraph }, null, 2)}\n</script>`;

  // Render meaningful body content inside #root for SSR / SEO crawlers
  let bodyContentHtml = '';

  if (isArticle) {
    bodyContentHtml = `
      <main className="relative min-h-screen bg-slate-50/50 pb-20 pt-8">
        <nav aria-label="Breadcrumb" className="mx-auto max-w-4xl px-6 my-4 text-xs font-semibold text-slate-500">
          <a href="/">Ana Sayfa</a> &gt; <a href="/blog">Blog</a> &gt; <span>${meta.h1Title}</span>
        </nav>
        <article className="mx-auto max-w-4xl px-6 bg-white rounded-3xl p-8 border border-slate-100 shadow-md">
          <header className="border-b border-slate-100 pb-6 mb-6">
            ${meta.category ? `<span className="inline-block rounded-full bg-primary/10 px-3 py-1 text-xs font-bold text-primary mb-3">${meta.category}</span>` : ''}
            <h1 className="text-3xl font-black text-slate-900 md:text-4xl leading-tight mb-4">${meta.h1Title}</h1>
            <div className="text-xs font-bold text-slate-400 uppercase tracking-tighter">
              Yazar: ${meta.authorName || 'Fullematematiği Kadrosu'} | Güncelleme: ${new Date(meta.updatedAt || meta.publishedAt || Date.now()).toLocaleDateString('tr-TR')}
            </div>
          </header>
          ${meta.coverImage ? `<div className="w-full max-h-[400px] overflow-hidden rounded-2xl mb-6"><img src="${meta.coverImage}" alt="${meta.h1Title}" className="w-full h-full object-cover"/></div>` : ''}
          <div className="prose max-w-none text-slate-700 leading-relaxed space-y-4">
            ${meta.articleBodyHtml || ''}
          </div>
          ${meta.faq && meta.faq.length > 0 ? `
            <section className="mt-10 rounded-2xl bg-slate-50 p-6 border border-slate-200">
              <h2 className="text-xl font-black text-slate-900 mb-4">Sıkça Sorulan Sorular</h2>
              <div className="space-y-4">
                ${meta.faq.map(f => `
                  <div className="bg-white p-4 rounded-xl border border-slate-100">
                    <h3 className="font-bold text-slate-900 text-sm mb-1">${f.question}</h3>
                    <p className="text-xs text-slate-600 leading-relaxed">${f.answer}</p>
                  </div>
                `).join('')}
              </div>
            </section>
          ` : ''}
          <section className="mt-8 rounded-2xl bg-primary/5 p-6 border border-primary/10">
            <h3 className="font-extrabold text-slate-900 text-sm mb-3">Diğer Alakalı Matematik Rehberleri &amp; Konular</h3>
            <div className="flex flex-wrap gap-2">
              <a href="/blog/oran-oranti" className="px-3 py-1.5 rounded-lg bg-white border border-slate-200 text-xs font-bold text-slate-700 hover:text-primary">Oran Orantı Konu Anlatımı</a>
              <a href="/blog/yas-problemleri" className="px-3 py-1.5 rounded-lg bg-white border border-slate-200 text-xs font-bold text-slate-700 hover:text-primary">Yaş Problemleri Konu Anlatımı</a>
              <a href="/blog/mutlak-deger" className="px-3 py-1.5 rounded-lg bg-white border border-slate-200 text-xs font-bold text-slate-700 hover:text-primary">Mutlak Değer Konu Anlatımı</a>
              <a href="/blog/tyt-matematik-konulari" className="px-3 py-1.5 rounded-lg bg-white border border-slate-200 text-xs font-bold text-slate-700 hover:text-primary">TYT Matematik Konuları</a>
              <a href="/blog/lgs-matematik-konulari" className="px-3 py-1.5 rounded-lg bg-white border border-slate-200 text-xs font-bold text-slate-700 hover:text-primary">LGS Matematik Konuları</a>
              <a href="/blog/9-sinif-matematik-konulari" className="px-3 py-1.5 rounded-lg bg-white border border-slate-200 text-xs font-bold text-slate-700 hover:text-primary">9. Sınıf Matematik Konuları</a>
            </div>
          </section>
        </article>
      </main>
    `;
  } else if (meta.path === '/blog') {
    const blogListHtml = FALLBACK_BLOGS.map(b => `
      <article className="rounded-2xl border border-slate-100 bg-white p-6 shadow-sm">
        <h2 className="text-xl font-bold text-slate-900 mb-2">
          <a href="/blog/${b.slug}" className="hover:text-primary">${b.title}</a>
        </h2>
        <p className="text-sm text-slate-600 mb-4">${b.excerpt}</p>
        <a href="/blog/${b.slug}" className="text-xs font-bold text-primary">Devamını Oku &rarr;</a>
      </article>
    `).join('\n');

    bodyContentHtml = `
      <main className="mx-auto max-w-7xl px-6 py-12">
        <h1 className="text-4xl font-black text-slate-900 mb-4">${meta.heading}</h1>
        <p className="text-lg text-slate-600 mb-8">${meta.intro}</p>
        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
          ${blogListHtml}
        </div>
      </main>
    `;
  } else {
    bodyContentHtml = `
      <main className="mx-auto max-w-7xl px-6 py-12">
        <h1 className="text-4xl font-black text-slate-900 mb-4">${meta.heading || fullTitle}</h1>
        <p className="text-lg text-slate-600 mb-8">${meta.intro || meta.description}</p>
      </main>
    `;
  }

  // Replace head tags in baseHtmlTemplate
  let renderedHtml = baseHtmlTemplate;

  // Replace Title
  renderedHtml = renderedHtml.replace(
    /<title>.*?<\/title>/i,
    `<title>${fullTitle}</title>`
  );

  // Replace Description
  renderedHtml = renderedHtml.replace(
    /<meta name="description" content=".*?" \/>/i,
    `<meta name="description" content="${meta.description}" />`
  );

  // Replace Keywords
  if (meta.keywords) {
    renderedHtml = renderedHtml.replace(
      /<meta name="keywords" content=".*?" \/>/i,
      `<meta name="keywords" content="${meta.keywords}" />`
    );
  }

  // Replace Canonical
  renderedHtml = renderedHtml.replace(
    /<link rel="canonical" href=".*?" \/>/i,
    `<link rel="canonical" href="${canonicalUrl}" />`
  );

  // Replace Robots
  renderedHtml = renderedHtml.replace(
    /<meta name="robots" content=".*?" \/>/i,
    `<meta name="robots" content="${robotsContent}" />`
  );

  // Replace OG Tags
  renderedHtml = renderedHtml.replace(
    /<meta property="og:title" content=".*?" \/>/i,
    `<meta property="og:title" content="${fullTitle}" />`
  );
  renderedHtml = renderedHtml.replace(
    /<meta property="og:description" content=".*?" \/>/i,
    `<meta property="og:description" content="${meta.description}" />`
  );
  renderedHtml = renderedHtml.replace(
    /<meta property="og:url" content=".*?" \/>/i,
    `<meta property="og:url" content="${canonicalUrl}" />`
  );
  renderedHtml = renderedHtml.replace(
    /<meta property="og:image" content=".*?" \/>/i,
    `<meta property="og:image" content="${ogImage}" />`
  );
  renderedHtml = renderedHtml.replace(
    /<meta property="og:type" content=".*?" \/>/i,
    `<meta property="og:type" content="${isArticle ? 'article' : 'website'}" />`
  );

  // Inject JSON-LD Schema before </head>
  renderedHtml = renderedHtml.replace('</head>', `${jsonLdHtml}\n</head>`);

  // Inject Body Content inside <div id="root">
  renderedHtml = renderedHtml.replace(
    '<div id="root"></div>',
    `<div id="root">${bodyContentHtml}</div>`
  );

  return renderedHtml;
}

// 2. Pre-render process
console.log('🚀 Starting Antigravity SSG & Pre-rendering engine...');

let prerenderedCount = 0;

// Render static main site pages
for (const page of STATIC_PAGES) {
  const pageHtml = generatePageHtml(page);
  let targetFilePath;
  if (page.path === '/') {
    targetFilePath = path.join(DIST_DIR, 'index.html');
  } else {
    const routeDir = path.join(DIST_DIR, page.path.slice(1));
    fs.mkdirSync(routeDir, { recursive: true });
    targetFilePath = path.join(routeDir, 'index.html');
  }
  fs.writeFileSync(targetFilePath, pageHtml, 'utf8');
  prerenderedCount++;
  console.log(`  ✓ Pre-rendered static page: ${page.path} -> ${targetFilePath}`);
}

// Render all static blog pages from FALLBACK_BLOGS
for (const post of FALLBACK_BLOGS) {
  const blogMeta = {
    path: `/blog/${post.slug}`,
    title: post.metaTitle || `${post.title} | Fullematematiği`,
    h1Title: post.title,
    description: post.description || post.excerpt || post.title,
    keywords: post.targetKeyword ? `${post.targetKeyword}, ${post.relatedKeywords ? post.relatedKeywords.join(', ') : ''}` : 'matematik konuları, Fullematematiği',
    type: 'article',
    category: post.category,
    coverImage: post.coverImage,
    publishedAt: post.createdAt,
    updatedAt: post.updatedAt,
    authorName: post.author?.name,
    articleBodyHtml: post.content,
    faq: post.faq || [],
    priority: '0.8',
    changefreq: 'weekly'
  };

  const blogHtml = generatePageHtml(blogMeta);
  const blogRouteDir = path.join(DIST_DIR, 'blog', post.slug);
  fs.mkdirSync(blogRouteDir, { recursive: true });
  const targetFilePath = path.join(blogRouteDir, 'index.html');
  fs.writeFileSync(targetFilePath, blogHtml, 'utf8');
  prerenderedCount++;
  console.log(`  ✓ Pre-rendered blog post: /blog/${post.slug}`);
}

console.log(`🎉 Pre-rendering complete! Generated ${prerenderedCount} HTML files with full SEO metadata.`);

// 3. Generate sitemap.xml
console.log('🗺️ Generating clean sitemap.xml...');

let sitemapXml = `<?xml version="1.0" encoding="UTF-8"?>\n`;
sitemapXml += `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n`;

for (const page of STATIC_PAGES) {
  sitemapXml += `  <url>\n`;
  sitemapXml += `    <loc>${BASE_URL}${page.path === '/' ? '' : page.path}</loc>\n`;
  sitemapXml += `    <changefreq>${page.changefreq}</changefreq>\n`;
  sitemapXml += `    <priority>${page.priority}</priority>\n`;
  sitemapXml += `  </url>\n`;
}

for (const post of FALLBACK_BLOGS) {
  const lastMod = post.updatedAt ? new Date(post.updatedAt).toISOString().split('T')[0] : new Date().toISOString().split('T')[0];
  sitemapXml += `  <url>\n`;
  sitemapXml += `    <loc>${BASE_URL}/blog/${post.slug}</loc>\n`;
  sitemapXml += `    <lastmod>${lastMod}</lastmod>\n`;
  sitemapXml += `    <changefreq>weekly</changefreq>\n`;
  sitemapXml += `    <priority>0.8</priority>\n`;
  sitemapXml += `  </url>\n`;
}

sitemapXml += `</urlset>`;

// Write sitemap to dist and public
fs.writeFileSync(path.join(DIST_DIR, 'sitemap.xml'), sitemapXml, 'utf8');
fs.writeFileSync(path.join(PUBLIC_DIR, 'sitemap.xml'), sitemapXml, 'utf8');
console.log(`  ✓ Written sitemap.xml to dist/sitemap.xml and public/sitemap.xml with ${STATIC_PAGES.length + FALLBACK_BLOGS.length} URLs.`);

// 4. Copy robots.txt to dist/robots.txt
const robotsPublicPath = path.join(PUBLIC_DIR, 'robots.txt');
if (fs.existsSync(robotsPublicPath)) {
  fs.copyFileSync(robotsPublicPath, path.join(DIST_DIR, 'robots.txt'));
  console.log(`  ✓ Copied robots.txt to dist/robots.txt`);
}

console.log('✅ SSG & SEO pre-rendering process completed successfully!');
